name: facecloud
services:
  db:
    image: postgres:16.4-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "$DB_NAME" ]
      interval: 30s
      timeout: 10s
      retries: 5
  app:
    build: .
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - api:/app
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db:
  api:
